### ISSUE TITLE
咨询

### ISSUE THREAD

**Issue by androidzhang** [toly1994328/Sound#1]
作者你在合肥发展吗

**Comment by toly1994328** [comment]
干嘛，要挖我吗?

**Comment by androidzhang** [comment]
挖毛啊

**Comment by LiWeiQiangAndroid** [comment]
闪退
java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.FileInputStream.close()' on a null object reference
        at top.toly.sound.audio.effect.PCMAudioPlayerWithRate$PlayRunnable.run(PCMAudioPlayerWithRate.java:152)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:760)
